name: Azure Static Web Apps CI/CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Deploy static file
    steps:
      - uses: actions/checkout@v4
      - name: Stage site
        run: |
          mkdir -p site
          cp index.html site/index.html
          cp staticwebapp.config.json site/staticwebapp.config.json
      - name: Deploy
        @1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_DUNE_014D74810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "site"
          api_location: ""
          output_location: ""
          skip_app_build: true
